# -*- coding: utf-8 -*-
"""Indian_Pincode_Boundary_Mapping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y6au0B3fGvzqhIf2nKVSlcGu6GN3PLUH

## **Indian Pincode Boundary Visualization using GeoPandas**
A geospatial analysis project for visualizing Indian PIN code boundaries using GeoPandas.

Author: Tanuja Modak

# Indian Pincode Boundary Mapping

This notebook works with Indian pincode boundary data and pincode attribute data.

The workflow includes:

- Loading pincode boundary polygons
- Merging administrative information using pincode
- State-wise visualization
- District-wise visualization
- Exporting processed GIS data
- Creating indexed pincode maps for districts
"""

import os
from google.colab import files
import geopandas as gpd
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import matplotlib.colors
import matplotlib.patheffects as pe

"""Please download the following files before running this notebook:

### Required Files

1. **INDIAN_PINCODE_BOUNDARY.geojson**
   - Download Link: https://drive.google.com/file/d/1dLpsz5_6GDONggo_1ANOC5BEPj21rLc1/view?usp=sharing

2. **india_pincode_lat_long.csv**
   - Download Link: https://drive.google.com/file/d/1EngXrLaRhm7LmDmpSzsWklt1GcRxtiC_/view?usp=sharing
"""

required_files = [
    "INDIAN_PINCODE_BOUNDARY.geojson",
    "india_pincode_lat_long.csv"
]

missing = [
    f for f in required_files
    if f not in os.listdir("/content")
]

if missing:
    print("Missing:", missing)
    files.upload()
else:
    print("Files already available.")

gdf = gpd.read_file(
    "/content/INDIAN_PINCODE_BOUNDARY.geojson"
)

pincode_coordinates = pd.read_csv(
    "/content/india_pincode_lat_long.csv",
    low_memory=False
)

print("GeoJSON Shape :", gdf.shape)
print("CSV Shape :", pincode_coordinates.shape)

display(
    pd.DataFrame(
        [gdf.columns.tolist()]
    )
)

display(
    pd.DataFrame(
        [pincode_coordinates.columns.tolist()]
    )
)

gdf.head(5)

pincode_coordinates.head(5)

gdf["Pincode"] = pd.to_numeric(
    gdf["Pincode"],
    errors="coerce"
)

pincode_coordinates["Pincode"] = pd.to_numeric(
    pincode_coordinates["Pincode"],
    errors="coerce"
)

coords_unique = (
    pincode_coordinates
    .sort_values("Pincode")
    .drop_duplicates("Pincode")
)

map_gdf = gdf.merge(
    coords_unique,
    on="Pincode",
    how="left"
)

print("GeoJSON Rows :", len(gdf))
print("Merged Rows :", len(map_gdf))

print(
    "StateName Filled:",
    map_gdf["StateName"].notna().sum()
)

print(
    "District Filled:",
    map_gdf["District"].notna().sum()
)

print(
    "Latitude Filled:",
    map_gdf["Latitude"].notna().sum()
)

display(
    pd.DataFrame(
        [map_gdf.columns.tolist()]
    )
)

map_gdf.to_file(
    "/content/MERGED_INDIAN_PINCODE_BOUNDARY.gpkg",
    driver="GPKG"
)

"""**State Analysis**"""

states = sorted(
    map_gdf["StateName"]
    .dropna()
    .unique()
)

print("Available States:\n")

for state in states:
    print(state)

selected_state = input(
    "\nEnter State Name: "
).strip().upper()

state_map = map_gdf[
    map_gdf["StateName"]
    .str.upper()
    == selected_state
].copy()

print(
    f"\nRows Found: {len(state_map)}"
)

print(
    f"Pincodes: {state_map['Pincode'].nunique()}"
)

print(
    f"Districts: {state_map['District'].nunique()}"
)

"""**STATE MAP VISUALIZATION**"""

state_map["ColorID"] = np.arange(
    len(state_map)
)

state_boundary = state_map.dissolve()

fig, ax = plt.subplots(
    figsize=(14,14)
)

state_map.plot(
    column="ColorID",
    cmap="turbo",
    edgecolor="white",
    linewidth=0.15,
    ax=ax
)

state_boundary.boundary.plot(
    ax=ax,
    color="black",
    linewidth=1.5
)

ax.set_title(
    f"{selected_state} Pincode Map",
    fontsize=20,
    fontweight="bold"
)

ax.axis("off")

plt.show()

"""**State Export Data**"""

csv_name = (
    f"{selected_state}_"
    f"{state_map['Pincode'].nunique()}_Pincodes.csv"
)

state_export = state_map.drop(
    columns=["geometry"],
    errors="ignore"
)

state_export.to_csv(csv_name, index=False)
files.download(csv_name)

print("Saved:", csv_name)

"""**District Analysis**"""

districts = sorted(
    state_map["District"]
    .dropna()
    .unique()
)

print(
    f"Total Districts: {len(districts)}\n"
)

for d in districts:
    print(d)

selected_district = input(
    "\nEnter District Name: "
).strip().upper()

district_map = map_gdf[
    map_gdf["District"]
    .astype(str)
    .str.upper()
    == selected_district
].copy()

print(
    f"\nRows Found: {len(district_map)}"
)

print(
    "State(s):",
    district_map["StateName"]
    .dropna()
    .unique()
)

"""**DISTRICT MAP VISUALIZATION**"""

district_map["Index"] = range(
    1,
    len(district_map) + 1
)

district_map["ColorID"] = np.arange(
    len(district_map)
)

district_boundary = district_map.dissolve()

fig, ax = plt.subplots(
    figsize=(12,12)
)

district_map.plot(
    column="ColorID",
    cmap="turbo",
    edgecolor="white",
    linewidth=0.2,
    ax=ax
)

district_boundary.boundary.plot(
    ax=ax,
    color="black",
    linewidth=1.5
)

for _, row in district_map.iterrows():

    try:

        point = row.geometry.representative_point()

        txt = ax.text(
            point.x,
            point.y,
            str(row["Index"]),
            color="white",
            fontsize=8,
            fontweight="bold",
            ha="center",
            va="center"
        )

        txt.set_path_effects([
            pe.withStroke(
                linewidth=1.5,
                foreground="black"
            )
        ])

    except:
        pass

ax.set_title(
    f"{selected_district} District "
    f"({len(district_map)} Pincodes)",
    fontsize=18,
    fontweight="bold"
)

ax.axis("off")

plt.show()

"""**INDEX FOR ABOVE DISTRICT MAP**"""

index_table = district_map[
    [
        "Index",
        "Pincode",
        "Office_Name",
        "Division",
        "District",
        "StateName"
    ]
].sort_values("Index")

display(index_table)

output_filename = f"{selected_state}_{selected_district}_pincode_index.csv"
index_table.to_csv(output_filename, index=False)
files.download(output_filename)